### ISSUE TITLE
Story - Automation - Develop standalone QA UI automation app

### ISSUE THREAD

**Issue by RehabAbotalep** [DevOpsVisions/question2answer-automation-toolkit#1]
```[tasklist]
### Tasks
- [ ] To Run from the command line
- [ ] To be independent from any machine (it will be tested on a new VM)
- [ ] To have Releases on GitHub
```
